---
name: Test
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
          
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        use_oidc: true
