---
name: Test
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.21"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
          
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
